#!/usr/bin/env node
/**
 * Learn From Failure Script (ES Module)
 * 
 * Analyzes failures and extracts lessons for continuous improvement.
 * Part of the auto-learner skill.
 * 
 * Uses JSON storage to avoid external dependencies.
 * 
 * Usage:
 *   node learn_from_failure.js --list
 *   node learn_from_failure.js --search "keyword"
 *   node learn_from_failure.js --pattern "error pattern" --message "lesson" [--severity HIGH]
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Colors
const colors = {
    reset: '\x1b[0m',
    red: '\x1b[31m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    blue: '\x1b[34m',
    cyan: '\x1b[36m',
    gray: '\x1b[90m',
    bold: '\x1b[1m'
};

// Find project root (.agent folder)
function findProjectRoot() {
    let current = process.cwd();
    while (current !== path.dirname(current)) {
        if (fs.existsSync(path.join(current, '.agent'))) {
            return current;
        }
        current = path.dirname(current);
    }
    return process.cwd();
}

const projectRoot = findProjectRoot();
const lessonsPath = path.join(projectRoot, '.agent', 'knowledge', 'lessons-learned.json');

// Ensure lessons file exists
function ensureLessonsFile() {
    const dir = path.dirname(lessonsPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    if (!fs.existsSync(lessonsPath)) {
        fs.writeFileSync(lessonsPath, JSON.stringify({ lessons: [] }, null, 2));
    }
}

// Load lessons
function loadLessons() {
    ensureLessonsFile();
    try {
        const content = fs.readFileSync(lessonsPath, 'utf8');
        const data = JSON.parse(content);
        return Array.isArray(data.lessons) ? data.lessons : [];
    } catch {
        return [];
    }
}

// Save lessons
function saveLessons(lessons) {
    ensureLessonsFile();
    const data = {
        _comment: "Lessons Learned - Auto-generated by auto-learner skill",
        updatedAt: new Date().toISOString(),
        lessons
    };
    fs.writeFileSync(lessonsPath, JSON.stringify(data, null, 2));
}

// Generate lesson ID
function generateId(lessons) {
    const existing = lessons.map(l => l.id).filter(Boolean);
    let maxNum = 0;
    for (const id of existing) {
        const match = id.match(/LEARN-(\d+)/);
        if (match) {
            maxNum = Math.max(maxNum, parseInt(match[1]));
        }
    }
    return `LEARN-${String(maxNum + 1).padStart(3, '0')}`;
}

// Add new lesson
function addLesson(pattern, message, severity = 'HIGH', trigger = '') {
    const lessons = loadLessons();

    // Check for duplicate pattern
    const exists = lessons.some(l => l.pattern === pattern);
    if (exists) {
        console.log(`${colors.yellow}⚠️  Lesson with this pattern already exists${colors.reset}`);
        return null;
    }

    const lesson = {
        id: generateId(lessons),
        pattern,
        severity,
        message,
        date: new Date().toISOString().split('T')[0],
        trigger: trigger || 'manual',
        fix_applied: true
    };

    lessons.push(lesson);
    saveLessons(lessons);

    return lesson;
}

// List all lessons
function listLessons() {
    const lessons = loadLessons();

    console.log(`${colors.cyan}╔════════════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.cyan}║${colors.reset}  📚 Lessons Learned                     ${colors.cyan}║${colors.reset}`);
    console.log(`${colors.cyan}╚════════════════════════════════════════╝${colors.reset}`);
    console.log(`${colors.gray}Total: ${lessons.length} lessons${colors.reset}\n`);

    if (lessons.length === 0) {
        console.log(`${colors.yellow}No lessons recorded yet.${colors.reset}`);
        return;
    }

    for (const lesson of lessons) {
        const severityColor = {
            CRITICAL: colors.red,
            HIGH: colors.yellow,
            MEDIUM: colors.blue,
            LOW: colors.gray
        }[lesson.severity] || colors.gray;

        console.log(`${colors.bold}${lesson.id}${colors.reset} [${severityColor}${lesson.severity}${colors.reset}]`);
        console.log(`  ${colors.gray}Pattern:${colors.reset} ${lesson.pattern}`);
        console.log(`  ${colors.gray}Date:${colors.reset} ${lesson.date}`);
        console.log('');
    }
}

// Search lessons
function searchLessons(keyword) {
    const lessons = loadLessons();
    const lowerKeyword = keyword.toLowerCase();

    const matches = lessons.filter(l =>
        l.pattern.toLowerCase().includes(lowerKeyword) ||
        l.message.toLowerCase().includes(lowerKeyword) ||
        l.id.toLowerCase().includes(lowerKeyword)
    );

    console.log(`${colors.cyan}🔍 Search: "${keyword}"${colors.reset}`);
    console.log(`${colors.gray}Found: ${matches.length} lessons${colors.reset}\n`);

    for (const lesson of matches) {
        console.log(`${colors.bold}${lesson.id}${colors.reset}: ${lesson.pattern}`);
        console.log(`  ${colors.gray}${lesson.message.split('\n')[0]}${colors.reset}`);
        console.log('');
    }
}

// Parse arguments
const args = process.argv.slice(2);

if (args.includes('--list') || args.includes('-l')) {
    listLessons();
} else if (args.includes('--search') || args.includes('-s')) {
    const idx = args.findIndex(a => a === '--search' || a === '-s');
    const keyword = args[idx + 1];
    if (keyword) {
        searchLessons(keyword);
    } else {
        console.log(`${colors.red}Error: --search requires a keyword${colors.reset}`);
    }
} else if (args.includes('--pattern') || args.includes('-p')) {
    const patternIdx = args.findIndex(a => a === '--pattern' || a === '-p');
    const messageIdx = args.findIndex(a => a === '--message' || a === '-m');
    const severityIdx = args.findIndex(a => a === '--severity');
    const triggerIdx = args.findIndex(a => a === '--trigger');

    const pattern = patternIdx >= 0 ? args[patternIdx + 1] : null;
    const message = messageIdx >= 0 ? args[messageIdx + 1] : null;
    const severity = severityIdx >= 0 ? args[severityIdx + 1] : 'HIGH';
    const trigger = triggerIdx >= 0 ? args[triggerIdx + 1] : '';

    if (!pattern || !message) {
        console.log(`${colors.red}Error: --pattern and --message are required${colors.reset}`);
        console.log(`Usage: node learn_from_failure.js --pattern "pattern" --message "lesson message"`);
        process.exit(1);
    }

    const lesson = addLesson(pattern, message, severity, trigger);
    if (lesson) {
        console.log(`${colors.green}📚 Learned: [${lesson.id}] - ${pattern}${colors.reset}`);
    }
} else {
    // Show help
    console.log(`${colors.cyan}auto-learner - Learn from failures${colors.reset}
  
${colors.bold}Usage:${colors.reset}
  node learn_from_failure.js --list                    List all lessons
  node learn_from_failure.js --search "keyword"        Search lessons
  node learn_from_failure.js --pattern "..." --message "..."  Add lesson

${colors.bold}Options:${colors.reset}
  -l, --list              List all lessons
  -s, --search <keyword>  Search lessons
  -p, --pattern <text>    Error pattern (required for add)
  -m, --message <text>    Lesson message (required for add)
  --severity <level>      CRITICAL, HIGH, MEDIUM, LOW (default: HIGH)
  --trigger <text>        What triggers this lesson
`);
}
