/**
 * @fileoverview Proposal Generator for Auto-Updating Flow
 * Generates markdown instructions for AI agents to update skills
 */

import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { KNOWLEDGE_DIR, LESSONS_PATH, AGENT_DIR } from "./config.js";
import { loadSettings } from "./settings.js";
import { loadKnowledge } from "./recall.js";

/** Proposals directory */
const PROPOSALS_DIR = path.join(KNOWLEDGE_DIR, "proposals");

/** Dismissed proposals file */
const DISMISSED_FILE = path.join(PROPOSALS_DIR, "dismissed.yaml");

/**
 * Get lessons that qualify for proposals (hitCount >= threshold)
 * @returns {Array<{ lesson: object, proposalPath: string }>}
 */
export function getQualifyingLessons() {
    const settings = loadSettings();
    const threshold = settings.updateThreshold || 5;
    const db = loadKnowledge();

    if (!db.lessons) return [];

    const dismissed = loadDismissed();

    return db.lessons
        .filter(l => (l.hitCount || 0) >= threshold && !dismissed.has(l.id))
        .map(lesson => ({
            lesson,
            proposalPath: path.join(PROPOSALS_DIR, `${lesson.id}.md`)
        }));
}

/**
 * Load dismissed proposal IDs
 * @returns {Set<string>}
 */
function loadDismissed() {
    try {
        if (fs.existsSync(DISMISSED_FILE)) {
            const data = yaml.load(fs.readFileSync(DISMISSED_FILE, "utf8")) || {};
            return new Set(data.dismissed || []);
        }
    } catch (e) { }
    return new Set();
}

/**
 * Dismiss a proposal
 * @param {string} lessonId
 */
export function dismissProposal(lessonId) {
    fs.mkdirSync(PROPOSALS_DIR, { recursive: true });
    const dismissed = loadDismissed();
    dismissed.add(lessonId);
    fs.writeFileSync(DISMISSED_FILE, yaml.dump({ dismissed: [...dismissed] }), "utf8");
}

/**
 * Generate proposal markdown for AI agent
 * @param {object} lesson - Lesson object
 * @returns {string} Markdown content
 */
export function generateProposalMarkdown(lesson) {
    const skillHint = guessSkillFromLesson(lesson);

    return `# 🤖 Skill Update Proposal

## Pattern Detected
| Field | Value |
|-------|-------|
| **ID** | \`${lesson.id}\` |
| **Hit Count** | ${lesson.hitCount || 0} |
| **Severity** | ${lesson.severity || "WARNING"} |
| **Last Hit** | ${lesson.lastHit || "N/A"} |

## Message
> ${lesson.message}

## Pattern (Regex)
\`\`\`
${lesson.pattern}
\`\`\`

---

## 📝 Suggested Action for AI Agent

Please update the relevant skill file to include this rule:

### Target File
\`${skillHint}\`

### Add to Rules Section
\`\`\`markdown
### ${lesson.message}
- Pattern: \`${lesson.pattern}\`
- Severity: ${lesson.severity || "WARNING"}
- Auto-learned from violations
\`\`\`

---

## How to Apply

1. **Copy this entire proposal**
2. **Paste to your AI coding agent** (Claude, Gemini, etc.)
3. **Ask:** "Update the skill file with this rule"

The AI agent will modify the appropriate \`.agent/skills/*/SKILL.md\` file.

---

*Generated by PikaKit v2.1.0*
`;
}

/**
 * Guess which skill file this lesson relates to
 * @param {object} lesson
 * @returns {string}
 */
function guessSkillFromLesson(lesson) {
    const pattern = (lesson.pattern || "").toLowerCase();
    const message = (lesson.message || "").toLowerCase();
    const combined = pattern + " " + message;

    // Frontend patterns
    if (combined.includes("react") || combined.includes("component") || combined.includes("hook") || combined.includes("usestate") || combined.includes("useeffect")) {
        return ".agent/skills/react-patterns/SKILL.md";
    }
    if (combined.includes("next") || combined.includes("getserverside") || combined.includes("getstaticprops") || combined.includes("app router")) {
        return ".agent/skills/nextjs-best-practices/SKILL.md";
    }
    if (combined.includes("css") || combined.includes("style") || combined.includes("tailwind") || combined.includes("classname")) {
        return ".agent/skills/frontend-design/SKILL.md";
    }

    // Backend patterns
    if (combined.includes("api") || combined.includes("fetch") || combined.includes("http") || combined.includes("endpoint") || combined.includes("rest")) {
        return ".agent/skills/api-patterns/SKILL.md";
    }
    if (combined.includes("database") || combined.includes("sql") || combined.includes("prisma") || combined.includes("query") || combined.includes("schema")) {
        return ".agent/skills/database-design/SKILL.md";
    }
    if (combined.includes("node") || combined.includes("express") || combined.includes("server") || combined.includes("middleware")) {
        return ".agent/skills/nodejs-best-practices/SKILL.md";
    }

    // Testing patterns
    if (combined.includes("test") || combined.includes("mock") || combined.includes("jest") || combined.includes("vitest") || combined.includes("expect")) {
        return ".agent/skills/testing-patterns/SKILL.md";
    }

    // TypeScript patterns
    if (combined.includes("typescript") || combined.includes("type") || combined.includes("interface") || combined.includes("generic") || combined.includes("any")) {
        return ".agent/skills/typescript-expert/SKILL.md";
    }

    // Security patterns
    if (combined.includes("security") || combined.includes("auth") || combined.includes("password") || combined.includes("token") || combined.includes("xss") || combined.includes("injection")) {
        return ".agent/skills/vulnerability-scanner/SKILL.md";
    }

    // Performance patterns
    if (combined.includes("performance") || combined.includes("memo") || combined.includes("lazy") || combined.includes("cache") || combined.includes("optimize")) {
        return ".agent/skills/performance-profiling/SKILL.md";
    }

    // Git patterns
    if (combined.includes("commit") || combined.includes("branch") || combined.includes("merge") || combined.includes("git")) {
        return ".agent/skills/git-conventions/SKILL.md";
    }

    // Default to clean-code for general patterns
    return ".agent/skills/clean-code/SKILL.md";
}

/**
 * Count pending proposals
 * @returns {number}
 */
export function countPendingProposals() {
    return getQualifyingLessons().length;
}

export default {
    getQualifyingLessons,
    dismissProposal,
    generateProposalMarkdown,
    countPendingProposals,
    PROPOSALS_DIR
};
