/**
 * SkillGenerator - Skill File Generator
 * 
 * Generates SKILL.md files from accumulated lessons.
 * Creates proper skill structure following SKILL_DESIGN_GUIDE.md.
 * 
 * @author PikaKit
 * @version 1.0.0
 */

import * as fs from 'fs';
import * as path from 'path';
import { Lesson } from './lessonStore';

export class SkillGenerator {
    private skillsDir: string;

    constructor(workspaceRoot: string) {
        this.skillsDir = path.join(workspaceRoot, '.agent', 'skills');
    }

    /**
     * Generate a skill from lessons
     */
    async generateSkill(skillName: string, lessons: Lesson[]): Promise<boolean> {
        try {
            // Validate skill name
            const normalizedName = this.normalizeSkillName(skillName);
            const skillDir = path.join(this.skillsDir, normalizedName);

            // Check if skill already exists
            if (fs.existsSync(skillDir)) {
                console.error(`Skill ${normalizedName} already exists`);
                return false;
            }

            // Create skill directory
            fs.mkdirSync(skillDir, { recursive: true });

            // Generate SKILL.md content
            const skillContent = this.generateSkillMd(normalizedName, lessons);
            fs.writeFileSync(path.join(skillDir, 'SKILL.md'), skillContent, 'utf8');

            // Update registry if exists
            await this.updateRegistry(normalizedName, lessons);

            console.log(`Generated skill: ${normalizedName}`);
            return true;
        } catch (error) {
            console.error('Failed to generate skill:', error);
            return false;
        }
    }

    /**
     * Generate SKILL.md content
     */
    private generateSkillMd(skillName: string, lessons: Lesson[]): string {
        const category = lessons[0]?.category || 'general';
        const patterns = lessons.map(l => l.pattern);
        const solutions = lessons.filter(l => l.solution).map(l => l.solution);

        const content = `---
name: ${skillName}
description: >-
  Auto-generated skill from ${lessons.length} learned patterns.
  Category: ${category}. Generated by PikaKit Skill Generator.
  Triggers on: ${this.generateTriggers(patterns)}.
metadata:
  category: "auto-generated"
  version: "1.0.0"
  triggers: "${this.generateTriggers(patterns)}"
  generated_from: ${lessons.length} lessons
  generated_at: "${new Date().toISOString()}"
---

# ${this.formatTitle(skillName)}

> **Purpose:** ${this.generatePurpose(category, patterns)}

---

## 📋 Learned Patterns

${this.generatePatternsSection(lessons)}

---

## 🔧 Quick Reference

${this.generateQuickReference(lessons)}

---

## ✅ Solutions

${this.generateSolutionsSection(lessons)}

---

## 📊 Statistics

| Metric | Value |
|--------|-------|
| **Patterns Learned** | ${lessons.length} |
| **Category** | ${category} |
| **Auto-Generated** | Yes |
| **Generated At** | ${new Date().toISOString().split('T')[0]} |

---

⚡ PikaKit v3.2.0
Auto-generated skill from learned patterns.
`;

        return content;
    }

    /**
     * Normalize skill name to kebab-case
     */
    private normalizeSkillName(name: string): string {
        return name
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '');
    }

    /**
     * Format skill name as title
     */
    private formatTitle(name: string): string {
        return name
            .split('-')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1))
            .join(' ');
    }

    /**
     * Generate triggers from patterns
     */
    private generateTriggers(patterns: string[]): string {
        // Extract key words from patterns
        const keywords = new Set<string>();

        for (const pattern of patterns) {
            const words = pattern.toLowerCase().match(/\b[a-z]{4,}\b/g) || [];
            for (const word of words.slice(0, 3)) {
                if (!['this', 'that', 'with', 'from', 'have', 'type'].includes(word)) {
                    keywords.add(word);
                }
            }
        }

        return Array.from(keywords).slice(0, 5).join(', ');
    }

    /**
     * Generate purpose description
     */
    private generatePurpose(category: string, patterns: string[]): string {
        const categoryMap: Record<string, string> = {
            'import': 'Handle import-related issues and ensure proper module loading',
            'type': 'Prevent type errors and ensure type safety',
            'react': 'Follow React best practices and avoid common pitfalls',
            'code-quality': 'Maintain code quality standards',
            'code-style': 'Enforce consistent code formatting',
            'null-safety': 'Handle null and undefined values safely',
            'async': 'Properly use async/await patterns',
            'general': 'Apply learned patterns from common errors'
        };

        return categoryMap[category] || `Apply learned patterns for ${category} related issues`;
    }

    /**
     * Generate patterns section
     */
    private generatePatternsSection(lessons: Lesson[]): string {
        return lessons.map((lesson, i) => {
            return `### ${i + 1}. ${lesson.pattern}

- **Context:** ${lesson.context}
- **Occurrences:** ${lesson.occurrences}
- **Source:** ${lesson.source}`;
        }).join('\n\n');
    }

    /**
     * Generate quick reference section
     */
    private generateQuickReference(lessons: Lesson[]): string {
        const references = lessons
            .filter(l => l.solution && l.solution !== 'See error message for details')
            .map(l => `- ${l.solution}`);

        if (references.length === 0) {
            return '- Review patterns above for common issues\n- Apply suggested fixes';
        }

        return references.join('\n');
    }

    /**
     * Generate solutions section
     */
    private generateSolutionsSection(lessons: Lesson[]): string {
        const solutions = lessons
            .filter(l => l.solution && l.solution !== 'See error message for details')
            .map((lesson, i) => {
                return `### ${lesson.pattern.substring(0, 40)}...

**Fix:** ${lesson.solution}`;
            });

        if (solutions.length === 0) {
            return 'Solutions are pattern-specific. Review the patterns above for guidance.';
        }

        return solutions.join('\n\n');
    }

    /**
     * Update registry.json if it exists
     */
    private async updateRegistry(skillName: string, lessons: Lesson[]): Promise<void> {
        const registryPath = path.join(this.skillsDir, 'registry.json');

        try {
            let registry: { skills: any[] } = { skills: [] };

            if (fs.existsSync(registryPath)) {
                const content = fs.readFileSync(registryPath, 'utf8');
                registry = JSON.parse(content);
            }

            // Add new skill to registry
            registry.skills.push({
                name: skillName,
                path: `./${skillName}/SKILL.md`,
                category: lessons[0]?.category || 'auto-generated',
                version: '1.0.0',
                autoGenerated: true,
                generatedAt: new Date().toISOString(),
                lessonsCount: lessons.length
            });

            fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2), 'utf8');
        } catch (error) {
            console.error('Failed to update registry:', error);
        }
    }
}
