/**
 * SkillGenerator Unit Tests
 * 
 * Tests skill file generation and SKILL.md validation
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

describe('SkillGenerator Logic', () => {
    let testDir: string;
    let skillsDir: string;

    beforeEach(() => {
        // Create temp directory
        testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pikakit-test-'));
        skillsDir = path.join(testDir, '.agent', 'skills');
        fs.mkdirSync(skillsDir, { recursive: true });
    });

    afterEach(() => {
        // Cleanup
        fs.rmSync(testDir, { recursive: true, force: true });
    });

    describe('Skill Directory Creation', () => {
        it('should create skill directory with correct name', () => {
            const skillName = 'typescript-imports';
            const skillDir = path.join(skillsDir, skillName);

            fs.mkdirSync(skillDir, { recursive: true });

            expect(fs.existsSync(skillDir)).toBe(true);
        });

        it('should normalize skill name to kebab-case', () => {
            const normalize = (name: string): string => {
                return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
            };

            expect(normalize('TypeScript Imports')).toBe('typescript-imports');
            expect(normalize('React_Hooks_Best')).toBe('react-hooks-best');
            expect(normalize('Code Quality!')).toBe('code-quality');
        });
    });

    describe('SKILL.md Generation', () => {
        it('should generate valid YAML frontmatter', () => {
            const lessons = [
                { id: 'TYPE-001', category: 'type', pattern: 'Type mismatch', solution: 'Fix type', occurrences: 3 }
            ];

            const generateSkillMd = (name: string, lessons: any[]): string => {
                return `---
name: ${name}
description: >-
  Auto-generated skill from ${lessons.length} learned patterns.
metadata:
  category: "auto-generated"
  version: "1.0.0"
---

# ${name}

## Patterns

${lessons.map((l, i) => `### ${i + 1}. ${l.pattern}`).join('\n\n')}
`;
            };

            const content = generateSkillMd('type-errors', lessons);

            expect(content).toContain('---');
            expect(content).toContain('name: type-errors');
            expect(content).toContain('Type mismatch');
        });

        it('should include all lessons in output', () => {
            const lessons = [
                { pattern: 'Pattern 1' },
                { pattern: 'Pattern 2' },
                { pattern: 'Pattern 3' }
            ];

            const content = lessons.map(l => `- ${l.pattern}`).join('\n');

            expect(content).toContain('Pattern 1');
            expect(content).toContain('Pattern 2');
            expect(content).toContain('Pattern 3');
        });

        it('should write SKILL.md to correct location', () => {
            const skillName = 'test-skill';
            const skillDir = path.join(skillsDir, skillName);
            fs.mkdirSync(skillDir, { recursive: true });

            const skillMd = '---\nname: test\n---\n# Test';
            const skillPath = path.join(skillDir, 'SKILL.md');

            fs.writeFileSync(skillPath, skillMd);

            expect(fs.existsSync(skillPath)).toBe(true);
            expect(fs.readFileSync(skillPath, 'utf8')).toContain('---');
        });
    });

    describe('Registry Update', () => {
        it('should create registry.json if not exists', () => {
            const registryPath = path.join(skillsDir, 'registry.json');
            const registry = { skills: [] };

            fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));

            expect(fs.existsSync(registryPath)).toBe(true);
        });

        it('should add new skill to registry', () => {
            const registryPath = path.join(skillsDir, 'registry.json');
            const registry: { skills: Array<{ name: string; path: string; autoGenerated: boolean }> } = { skills: [] };

            registry.skills.push({
                name: 'test-skill',
                path: './test-skill/SKILL.md',
                autoGenerated: true
            });

            fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));

            const content = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
            expect(content.skills).toHaveLength(1);
            expect(content.skills[0].autoGenerated).toBe(true);
        });
    });

    describe('Title Formatting', () => {
        it('should format skill name as title', () => {
            const formatTitle = (name: string): string => {
                return name.split('-').map(word =>
                    word.charAt(0).toUpperCase() + word.slice(1)
                ).join(' ');
            };

            expect(formatTitle('typescript-imports')).toBe('Typescript Imports');
            expect(formatTitle('react-hooks')).toBe('React Hooks');
            expect(formatTitle('code-quality')).toBe('Code Quality');
        });
    });

    describe('Trigger Generation', () => {
        it('should extract keywords from patterns', () => {
            const patterns = [
                'Cannot find name useState',
                'Cannot find name useEffect',
                'Import missing'
            ];

            const keywords = new Set<string>();
            for (const pattern of patterns) {
                const words = pattern.toLowerCase().match(/\b[a-z]{4,}\b/g) || [];
                for (const word of words.slice(0, 3)) {
                    if (!['this', 'that', 'with', 'from', 'have'].includes(word)) {
                        keywords.add(word);
                    }
                }
            }

            expect(keywords.has('cannot')).toBe(true);
            expect(keywords.has('find')).toBe(true);
            expect(keywords.has('name')).toBe(true);
        });
    });
});
